#! /bin/bash

# Function to read config file and return the correct host
function config_host {
    host_re=$1
    if [[ $# == 3 && $2 == "-t" ]]; then
        hosts=$3
    elif [[ $# == 1 ]]; then
        hosts=$(sed "4q;d" config)
    else
        error "Usage: one arg=host pattern or -t: provide list of hosts"
    fi
    echo "Not finished"
}

# Function to read config file and return the correct server
function config_server {
    server_re=$1
    servers=$(sed "7q;d" config)
}

# Function to parse the arguments
function parse_arg {
    return 1
}

# Error function
function error {
    echo "$@"
    exit 1
}

### Unit Tests ###

# Tests config_host to see if it returns the correct pattern, or correctly
# errors.
function test_config_host {
    RESULT=$(config_host "test" -t "sometest;helloworld;something")
    if [[ $RESULT == "Not finished" ]]; then
        error "Unimplemented: config_host"
    elif [[ $RESULT != "sometest" ]]; then
        error "config_host test failed, got $RESULT"
    fi
    echo "config_host test successfully conducted"
}

##### Main program #####
test_config_host
