#! /bin/bash

# Function to read config file and return the correct host or correct server
function config_pattern {
    pattern_re=$1
    if [[ $# == 3 && $2 == "-t" ]]; then
        names=$3
        types="tests"
    elif [[ $# == 2 && $2 == "-h" ]]; then
        names=$(sed "4q;d" config)
        types="hosts"
    elif [[ $# == 2 && $2 == "-s" ]]; then
        names=$(sed "7q;d" config)
        types="servers"
    else
        echo "Usage:"
        error "          config_pattern [pattern] [-h/-s/-t] [if -t: test sequence]"
    fi
    IFS=';' read -ra ARR <<< "$names"
    for h in "${ARR[@]}"; do
        if [[ "$h" =~ "$pattern_re" ]]; then
            echo "$h"
            return 0
        fi
    done
    error "Pattern \"$pattern_re\" matches no $types"
}

# Function to parse the arguments
function parse_arg {
    return 1
}

# Error function
function error {
    echo "$@"
    exit 1
}

### Unit Tests ###

# Tests config_pattern to see if it returns the correct pattern, or correctly
# errors.
function test_config_pattern {
    RESULT=$(config_pattern "test" -t "sometest;helloworld;something")
    if [[ $RESULT == "Not finished" ]]; then
        error "Unimplemented: config_pattern"
    elif [[ $RESULT != "sometest" ]]; then
        error "config_pattern test failed, got $RESULT"
    fi
    echo "config_pattern test successfully conducted"
}

##### Main program #####
test_config_pattern
