#! /bin/bash

# Function to read config file and return the correct host
function config_host {
    host_reg=$1
    grep "$host_reg" config
}

# Function to parse the arguments
function parse_arg {

}

echo $(config_host 1)
